# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "faktura"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Martin Scheidt"]
license = "ISC"
description = "faktura combines typst-letter-pro, typst-invoice, and TiefLetter into one Typst package for creating business letters, quotes, and invoices in a unified layout. It provides DIN-compliant formatting, reusable components, and minimal configurationâ€”ideal for freelancers, small businesses, and automated document workflows."
homepage = "https://github.com/kaat0/typst-faktura"
repository = "https://github.com/kaat0/typst-faktura"
keywords = ["invoice", "offer", "letter", "din5008"]
categories = ["office"]
disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

[template]
path = "template"
entrypoint = "invoice.typ"
# thumbnail = "thumbnail.png"
